-- =============================================================================
-- Generated by lightline to lualine theme converter
--   https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9
-- License: MIT License
-- =============================================================================

local colors = {
  color0   = "#262626",
  color1   = "#A4E400",
  color2   = "#62D8F1",
  color3   = "#444444",
  color4   = "#bcbcbc",
  color5   = "#5f5f5f",
  color6   = "#303030",
  color7   = "#FC1A70",
  color8   = "#AC7CFF",
  color9   = "#E7DC6D",
}

local monokai_tasty = {
  insert = {
    b = { fg = colors.color0, bg = colors.color1 },
    c = { fg = colors.color2, bg = colors.color3 },
    a = { fg = colors.color1, bg = colors.color3 , gui = "bold", },
  },
  inactive = {
    b = { fg = colors.color4, bg = colors.color5 },
    c = { fg = colors.color5, bg = colors.color6 },
    a = { fg = colors.color0, bg = colors.color5 , gui = "bold", },
  },
  replace = {
    b = { fg = colors.color0, bg = colors.color7 },
    c = { fg = colors.color7, bg = colors.color3 },
    a = { fg = colors.color7, bg = colors.color3 , gui = "bold", },
  },
  visual = {
    b = { fg = colors.color0, bg = colors.color8 },
    c = { fg = colors.color8, bg = colors.color3 },
    a = { fg = colors.color8, bg = colors.color3 , gui = "bold", },
  },
  normal = {
    b = { fg = colors.color0, bg = colors.color9 },
    c = { fg = colors.color9, bg = colors.color3 },
    a = { fg = colors.color9, bg = colors.color3 , gui = "bold", },
  },
  command = {
    b = { fg = colors.color0, bg = colors.color2 },
    a = { fg = colors.color2, bg = colors.color3 , gui = "bold", },
  },
}

return monokai_tasty